[build]
  command = "pnpm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "24"
  NETLIFY_TOOLBAR = "false"

[[redirects]]
  from = "/.well-known/avatar"
  to = "/bartveneman.png"
	# 200 tells Netlify this is a rewrite, not a redirect
  status = 200

[[redirects]]
  from = "/.well-known/avatar.png"
  to = "/bartveneman.png"
	# 200 tells Netlify this is a rewrite, not a redirect
  status = 200