[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
  from = "/.well-known/avatar"
  to = "/bartveneman.png"
	# 200 tells Netlify this is a rewrite, not a redirect
  status = 200

[[redirects]]
  from = "/.well-known/avatar.png"
  to = "/bartveneman.png"
	# 200 tells Netlify this is a rewrite, not a redirect
  status = 200